---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	incident_manager(incident_manager)
	web_tool(web_tool)
	app_tool(app_tool)
	db_tool(db_tool)
	cache_tool(cache_tool)
	aggregate(aggregate)
	summarizer(summarizer)
	__end__([<p>__end__</p>]):::last
	__start__ --> incident_manager;
	aggregate --> summarizer;
	app_tool --> incident_manager;
	cache_tool --> incident_manager;
	db_tool --> incident_manager;
	incident_manager -.-> aggregate;
	incident_manager -.-> app_tool;
	incident_manager -.-> cache_tool;
	incident_manager -.-> db_tool;
	incident_manager -.-> web_tool;
	web_tool --> incident_manager;
	summarizer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
